spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${LOCAL_DB_URL}  # 컨테이너의 포트와 데이터베이스 이름에 맞게 
    username: ${LOCAL_DB_USERNAME}  # Docker에서 설정한 POSTGRES_USER
    password: ${LOCAL_DB_PASSWORD} # Docker에서 설정한 POSTGRES_PASSWORD


