spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  security:
    user.name: ${SEC_USERNAME}
    user.password: ${SEC_PASSWORD}