spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update  # create는 기존 데이터가 있으면 데이터가 삭제될 수 있습니다. 일반적으로 'update' 또는 'validate'를 사용합니다.
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${LOCAL_DB_URL}  # 컨테이너의 포트와 데이터베이스 이름에 맞게 설정
    username: ${LOCAL_DB_USERNAME}  # Docker에서 설정한 POSTGRES_USER
    password: ${LOCAL_DB_PASSWORD} # Docker에서 설정한 POSTGRES_PASSWORD

  security:
    user:
      name: ${SEC_USERNAME}
      password: ${SEC_PASSWORD}
